<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPgxVG2y\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPgxVG2y/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPgxVG2y.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPgxVG2y\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerPgxVG2y\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'PgxVG2y',
    'container.build_id' => 'ea7d7379',
    'container.build_time' => 1557820401,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPgxVG2y');
